# render.yaml pour Durama

# --- Base de données ---
databases:
  - name: duramadb
    plan: free
    databaseName: durama
    user: durama_user

# --- Services web (backend Django) ---
services:
  - type: web
    name: durama-backend
    plan: free
    env: python
    runtime: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations --noinput || true
      python manage.py migrate --noinput || true
      # 🔹 Charger les données depuis data.json si le fichier existe
      if [ -f data.json ]; then
        echo "Chargement des données depuis data.json..."
        python manage.py loaddata data.json
      fi

    startCommand: "gunicorn Durama.wsgi"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: duramadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
