# render.yaml pour Durama

# --- Base de données ---
databases:
  - name: duramadb          # identifiant de la base dans Render
    plan: free              # plan gratuit
    databaseName: durama    # nom réel de la base dans PostgreSQL
    user: durama_user       # utilisateur de la base

# --- Services web (backend Django) ---
services:
  - type: web
    name: durama-backend     # nom du service Render
    plan: free
    env: python
    runtime: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations --noinput || true
      python manage.py migrate --noinput || true

    startCommand: "gunicorn Durama.wsgi"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: duramadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
