# Generated by Django 5.2.6 on 2025-09-30 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=150)),
                ('code_Couleur', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('courte_description', models.TextField(max_length=550)),
                ('longue_description', models.TextField(max_length=1500)),
                ('photo', models.FileField(blank=True, null=True, upload_to='imageCategorie/')),
                ('is_parent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updeated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAttribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numéro unique de la commande', max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('preparee', 'Préparée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('total_produits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporteur', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_suivi', models.CharField(blank=True, max_length=100, null=True)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(default='En préparation', max_length=50)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='DuramaProject.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('effectue', 'Effectué'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('methode', models.CharField(blank=True, choices=[('carte_bancaire', 'Carte bancaire'), ('paypal', 'PayPal'), ('virement', 'Virement bancaire'), ('cash_on_delivery', 'Paiement à la livraison'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo')], max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='DuramaProject.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Utilisateur propriétaire du panier', on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_detenteur_du_panier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DuramaProject.panier'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)])),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('sku', models.CharField(blank=True, error_messages={'null': 'Le SKU ne doit pas être null', 'unique': 'Le SKU doit être unique'}, max_length=150, null=True, unique=True)),
                ('type_produit', models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable')], max_length=50)),
                ('nom_vendeur', models.CharField(blank=True, max_length=150, null=True)),
                ('description_courte', models.TextField(default='...', max_length=1500)),
                ('description_longue', models.TextField(default='...', max_length=5000)),
                ('prix_fournisseur', models.DecimalField(decimal_places=2, help_text="Prix d'achat du produit chez le fournisseur", max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Le prix fournisseur ne peut pas être négatif')])),
                ('prix_promo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente calculé automatiquement', max_digits=15, null=True)),
                ('quantite', models.IntegerField(default=10)),
                ('etat_stock', models.CharField(choices=[('en_stock', 'En stock'), ('rupture_stock', 'Rupture de stock'), ('sur_commande', 'Sur commande')], default='en_stock', max_length=50)),
                ('largeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('longueur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hauteur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('materiau', models.CharField(blank=True, max_length=150, null=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('est_original', models.BooleanField(default=True)),
                ('caracteristiques', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('en_vedette', 'En vedette'), ('recommande', 'Est recommandé'), ('publie', 'Publié')], default='publie', max_length=50)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='produits/principales/')),
                ('vues', models.PositiveIntegerField(default=0)),
                ('nombres_ventes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='DuramaProject.categorie')),
                ('etiquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='DuramaProject.etiquette')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DuramaProject.produit')),
            ],
        ),
        migrations.CreateModel(
            name='AvisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=1500)),
                ('note', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='DuramaProject.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_fournisseur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prix_promo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantite', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='DuramaProject.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ContenuPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('is_variable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribut_valeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Valeur_d_attribut', to='DuramaProject.attribut')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenu', to='DuramaProject.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus_panier', to='DuramaProject.produit')),
                ('produit_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_variable', to='DuramaProject.produitvariable')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='DuramaProject.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DuramaProject.produit')),
                ('produit_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DuramaProject.produitvariable')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitVariableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/variantes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DuramaProject.produitvariable')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('courte_description', models.TextField(blank=True, max_length=550, null=True)),
                ('longue_description', models.TextField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_principale', to='DuramaProject.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='DuramaProject.subcategorie'),
        ),
        migrations.AddField(
            model_name='attribut',
            name='typeAttribut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_d_attribut', to='DuramaProject.typeattribut'),
        ),
        migrations.CreateModel(
            name='ProduitVariableAttribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='DuramaProject.attribut')),
                ('produit_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributs', to='DuramaProject.produitvariable')),
            ],
            options={
                'unique_together': {('produit_variable', 'attribut')},
            },
        ),
    ]
