# Generated by Django 5.2.6 on 2025-10-03 21:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0002_attribut_categorie_etiquette_typeattribut_commande_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='acheteur',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='vendeur',
        ),
        migrations.AddField(
            model_name='panier',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Addresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_url', models.URLField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code promotionnel unique à utiliser pour bénéficier de la remise.', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], default='percent', help_text='Type de remise : Fixe (montant) ou Pourcentage.', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=2, help_text='Montant de la remise. Exemple : 10.00 pour une réduction de 10 € ou 10.00 pour une remise de 10 %.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, default=10000, help_text='Limite pour une remise en pourcentage. Exemple : Si la remise est de 20 %, la réduction totale ne dépassera pas ce montant.', max_digits=10, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, default=10000, help_text='Montant minimum de commande pour appliquer ce code promo.', max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'utilisations du code promo. Laisser vide pour un usage illimité.", null=True)),
                ('current_uses', models.PositiveIntegerField(db_default=0, default=0, help_text="Nombre actuel d'utilisations du code promo.")),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'utilisations par utilisateur.", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le code promo est actuellement actif ou désactivé.')),
                ('start_date', models.DateTimeField(help_text='Date et heure de début de validité du code promo.')),
                ('end_date', models.DateTimeField(help_text='Date et heure de fin de validité du code promo.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du code promo.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour du code promo.')),
                ('eligible_users', models.ManyToManyField(blank=True, help_text='Utilisateurs éligibles pour ce code promo. Laisser vide pour tous les utilisateurs.', to=settings.AUTH_USER_MODEL)),
                ('target_categories', models.ManyToManyField(blank=True, help_text='Catégories ciblées par ce code promo.', to='DuramaProject.categorie')),
                ('target_products', models.ManyToManyField(blank=True, help_text='Produits ciblés par ce code promo.', to='DuramaProject.produit')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, help_text='Montant de la remise appliquée', max_digits=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DuramaProject.commande')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='DuramaProject.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
