# Generated by Django 5.2.6 on 2025-10-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0003_rename_acheteur_commande_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='gros_oeuvres',
            field=models.CharField(blank=True, choices=[('gros-oeuvres', 'Gros Oeuvres'), ('second-oeuvres', 'Second Oeuvres'), ('outillage', 'Outillage'), ('securité', 'Sécurité')], max_length=150, null=True),
        ),
    ]
