# Generated by Django 5.2.6 on 2025-10-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0004_categorie_gros_oeuvres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='gros_oeuvres',
            new_name='gros_categorie',
        ),
    ]
