# Generated by Django 5.2.6 on 2025-10-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0006_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='profil/'),
        ),
    ]
