# Generated by Django 5.2.6 on 2025-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0007_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribut',
            name='code_Couleur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
