# Generated by Django 5.2.6 on 2025-10-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0008_alter_attribut_code_couleur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenupanier',
            name='attribut_valeur',
        ),
        migrations.RemoveField(
            model_name='contenupanier',
            name='produit_variable',
        ),
    ]
