# Generated by Django 5.2.6 on 2025-10-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0009_remove_contenupanier_attribut_valeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenupanier',
            name='attribut_valeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Valeur_d_attribut', to='DuramaProject.attribut'),
        ),
        migrations.AddField(
            model_name='contenupanier',
            name='produit_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_variable', to='DuramaProject.produitvariable'),
        ),
    ]
