# Generated by Django 5.2.6 on 2025-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0010_contenupanier_attribut_valeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='etat_stock',
            field=models.CharField(choices=[('en stock', 'En stock'), ('rupture stock', 'Rupture de stock'), ('sur commande', 'Sur commande')], default='en_stock', max_length=50),
        ),
    ]
