# Generated by Django 5.2.6 on 2025-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0011_alter_produit_etat_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='livraison_gratuite',
            field=models.BooleanField(default=False),
        ),
    ]
