# Generated by Django 5.2.6 on 2025-11-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0012_produit_livraison_gratuite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('user', 'produit')},
        ),
    ]
