# Generated by Django 5.2.6 on 2026-01-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuramaProject', '0013_alter_favori_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenupanier',
            name='attribut_valeur',
        ),
        migrations.AddField(
            model_name='contenupanier',
            name='attributs',
            field=models.ManyToManyField(blank=True, related_name='contenus_panier', to='DuramaProject.attribut'),
        ),
    ]
